<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>name</key>
	<string>HTML (Django)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{% comment %}</string>
			<key>end</key>
			<string>{% endcomment %}</string>
			<key>name</key>
			<string>comment.block.django</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.line.django</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>storage.type.variable.django</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#template_filter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>end</key>
			<string>%}</string>
			<key>name</key>
			<string>storage.type.templatetag.django</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#template_tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#template_filter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>template_filter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(add|addslashes|apnumber|capfirst|center|cut|date|default|default_if_none|dictsort|dictsortreversed|divisibleby|escape|escapejs|filesizeformat|first|fix_ampersands|floatformat|force_escape|get_digit|intcomma|intword|iriencode|join|last|length|length_is|linebreaks|linebreaksbr|linenumbers|ljust|localize|localtime|lower|make_list|markdown|naturalday|naturaltime|ordinal|phone2numeric|pluralize|pprint|random|removetags|restructuredtext|rjust|safe|safeseq|slice|slugify|stringformat|striptags|textile|time|timesince|timeutil|timezone|title|truncatechars|truncatewords|truncatewords_html|unlocalize|unordered_list|upper|urlencode|urlize|urlizetrunc|utc|wordcount|wordwrap|yesno)\b</string>
					<key>name</key>
					<string>keyword.control.filter.django</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_.-]+</string>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
			</array>
		</dict>
		<key>template_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(as|autoescape|endautoescape|block|endblock|blocktrans|plural|endblocktrans|csrf_token|cycle|debug|extends|filter|endfilter|firstof|for|in|empty|endfor|get_available_languages|get_current_language|get_current_language_bidi|get_current_timezone|get_language_info|get_language_info_list|get_media_prefix|get_static_prefix|if|and|or|not|elif|else|endif|ifchanged|endifchanged|ifequal|endifequal|ifnotequal|endifnotequal|include|load|from|localize|endlocalize|localtime|endlocaltime|lorem|now|regroup|by|spaceless|endspaceless|ssi|static|templatetag|timezone|endtimezone|trans|url|widthratio|with|endwith)\b</string>
					<key>name</key>
					<string>keyword.control.tag.django</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.django</string>
</dict>
</plist>
